### ISSUE TITLE
Create Dataset Description from csv input

### ISSUE THREAD

**Issue by nicholsn** [sibis-platform/redcap_rdf#11]
Take as input into the cube creation script an extra parameter for a csv file that provides the dataset metadata conforming to: https://www.w3.org/TR/vocab-data-cube/#metadata

- [x] Add a method to the Transformer object that takes a csv file
- [x] Validate that the csv file conforms to the file in redcap_rdf/tests/data/dataset.csv
- [x] Map data over to corresponding predicates (e.g., title --> dct:title, etc.)
- [x] Automatically add links to the data structure and slices

**Comment by nicholsn** [comment]
the URI for the dataset: http://sibis.sri.com/iri/ncanda-public-release-1.0.0	

this can be shortened to `prefix iri: <http://sibis.sri.com/iri/>`

**Comment by nicholsn** [comment]
@victorSRI the mapping file is now available...let me know if anything is missing or if there is extra info yuo do't need:

https://github.com/sibis-platform/redcap_rdf/blob/master/redcap_rdf/tests/data/mapping.csv

**Comment by victorSRI** [comment]
@nicholsn Where would the data structure and slices come from?

**Comment by nicholsn** [comment]
@victorSRI the data structure definition (DSD) comes from the `data dictionary` and the slices would come from a  argument similar to the `first_rows` argument to the Valdator.process method, only it could be any data element that could act as a dimension of the dataset.

For the DSD:
- the filename of the data dictionary can be used as the URI for the `a qb:DataStructureDefinition`
- the dimension components would come from a list of data elements passed to the transform
- the measures would be the remaining data elements
- the attributes would attach the units to at the `qb:MeasureProperty` level

For example, using the `redcap_rdf/tests/data/observations_datadict.csv`
```
:observation_datadict.csv a qb:DataStructureDefinition;
    qb:component 
    # The dimensions
        [ qb:dimension :subject; qb:order 1; qb:componentAttachment qb:Observation ],
        [ qb:dimension :arm; qb:order 2; qb:componentAttachment qb:Slice ],
        [ qb:dimension :visit; qb:order 3; qb:componentAttachment qb:Slice ];
        
    # The measure(s)
    qb:component [ qb:measure :site];
    qb:component [ qb:measure :sex];
    qb:component [ qb:measure :visit_age];
    qb:component [ qb:measure :race];
    
    # The attributes
    qb:component [ qb:attribute sibis:unitMeasure; 
                   qb:componentRequired "true"^^xsd:boolean;
                   qb:componentAttachment qb:MeaureProperty; ] ;
    
    # slices [use the template of `sibis:sliceBy{qb:order 1}{qb:order 2}...`
    qb:sliceKey sibis:sliceBySubjectArmVisit .
```

For the slices:
- Provide optional arguments for providing a label and a comment
- Use all `qb:order` > 1

For example, extending from the above:
```
eg:sliceBySubjectArmVisit a qb:SliceKey;
    rdfs:label "slice by subject arm visit"@en;
    rdfs:comment "Slice by grouping subject together, fixing arm and visit values"@en;
    qb:componentProperty :arm, :visit .
```

**Comment by victorSRI** [comment]
Ready for review and merge.
