### ISSUE TITLE
Create Observations from input csv files

### ISSUE THREAD

**Issue by nicholsn** [sibis-platform/redcap_rdf#13]
Create observations according to https://www.w3.org/TR/vocab-data-cube/#datasets.

- [x] Add a method(s) to the Transformer object that parses an input csv file and generates a set of observations grouped by slice
- [x] Verify that the datadict and csv file are consistent with each other using `redcap_rdf/tests/data/observation.csv` and  `redcap_rdf/tests/data/observation_datadict.csv`

**Comment by victorSRI** [comment]
The files are not consistent with each other. `observation.csv` has an additional field called "race_label" that does not appear in `observation_datadict.csv`.

**Comment by victorSRI** [comment]
Ready for review.  These commits are based on issue #11 as a starting point.

**Comment by nicholsn** [comment]
@victorSRI good point about the `_label`, REDCap outputs these fields as the mapping between the coded value for a categorical variable where the `_label` is the human readable text for the code. I think these can be ignored, as long as the datadict is a categorical variable.
